### ISSUE TITLE
myScroll.default is not a construtor

### ISSUE THREAD

**Issue by Today919** [bajian/vue-pull-to-refresh#4]
![image](https://user-images.githubusercontent.com/33539464/42436759-a4df11ce-838d-11e8-9f27-cc7cd8474510.png)
![image](https://user-images.githubusercontent.com/33539464/42436790-b9615bd4-838d-11e8-8050-a1b13b1e4f38.png)
您 好这个问题是什么情况  我把你整个pull-to-refresh引入的项目中 出现这个错误怎么解决呢

**Comment by bajian** [comment]
已经更新，请重新拉取最新的试下
